In [3]:
import numpy

In [42]:
class TrainIterator(object):
    '''Класс итератора для работы с обучающими данными. 
    
    Параметры
    ----------
    X : двумерный массив признаков размера n_samples x n_features
    y : массив/список правильных значений размера n_samples
    n_epoch : количество эпох обучения (default = 1)
    batch_size : размер пакета для шага SGD (default = 16)
    '''    
    def __init__(self, X, y, n_epoch=1, batch_size=16):
        self.X = numpy.array(X)
        self.y = numpy.array(y)
        self.n_epoch = n_epoch
        self.batch_size = batch_size
        self.n = (X.shape[0] * n_epoch) // batch_size
        self.cnt = -1
    
    def __iter__(self):
        '''Нужно для использования итератора в цикле for
        Здесь ничего менять не надо
        '''
        return self

    def __next__(self):
        '''Выдача следующего батча.
        
        Выход
        -------
        Метод возвращает очередной батч как из X, так и из y
        '''
        self.cnt += 1
        if self.cnt < self.n:
            i = self.cnt * self.batch_size - (self.X.shape[0] * ((self.cnt * self.batch_size) // self.X.shape[0]))
            j = i + self.batch_size
            k = j - self.X.shape[0] if j > self.X.shape[0] else -self.X.shape[0]
            return numpy.append(self.X[i:j], self.X[:k], axis=0)
        else:
            raise StopIteration

In [43]:
numpy.random.seed(2)
X = numpy.random.randint(100, size=(5, 3))
y = numpy.random.randint(100, size=10)
print(X)
print()
print(y)
print()
print(X[:-8])
print()
print(numpy.append(X[0:2], X[4:7], axis=0))


[[40 15 72]
 [22 43 82]
 [75  7 34]
 [49 95 75]
 [85 47 63]]

[31 90 20 37 39 67  4 42 51 38]

[]

[[40 15 72]
 [22 43 82]
 [85 47 63]]


In [44]:
iterator = TrainIterator(X, y, n_epoch=2, batch_size=2)
for a in iterator:
    print(a)

[[40 15 72]
 [22 43 82]]
[[75  7 34]
 [49 95 75]]
[[85 47 63]
 [40 15 72]]
[[22 43 82]
 [75  7 34]]
[[49 95 75]
 [85 47 63]]
